
project_id = "tglehsdmhzdntfftchtk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.chat-search]
verify_jwt = false

[functions.setup-vector-search]
verify_jwt = false
