// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tglehsdmhzdntfftchtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbGVoc2RtaHpkbnRmZnRjaHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTg5NjksImV4cCI6MjA2ODQzNDk2OX0.UsIWZqOysKD-jnPaI43Wzpt_Pj7s3Fubo4nShje1Tg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});